"""Change feedback.question to Text

Revision ID: 2e12a272c457
Revises: c68e85d91e8b
Create Date: 2025-08-31 16:17:37.081854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e12a272c457'
down_revision: Union[str, Sequence[str], None] = 'c68e85d91e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedbacks', 'question',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index('ix_profiles_full_name', 'profiles', ['full_name'], unique=False)
    op.create_index('ix_profiles_location', 'profiles', ['location'], unique=False)
    op.create_index('ix_resumes_user_updated', 'resumes', ['user_id', 'updated_at'], unique=False)
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_index('ix_resumes_user_updated', table_name='resumes')
    op.drop_index('ix_profiles_location', table_name='profiles')
    op.drop_index('ix_profiles_full_name', table_name='profiles')
    op.alter_column('feedbacks', 'question',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
